from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Any

from slm.checkpoints import DEFAULT_CHECKPOINTS, load_checkpoints, record_checkpoint
from slm.config import load_env_file
from slm.dataset import load_pool
from slm.publishing import (
    push_checkpoint,
    set_space_variable,
    render_model_card,
    upload_card,
    upload_directory,
)
from slm.reporting import Trial, aggregate
from slm.training import TrainResult

DEFAULT_DATA = Path("data/train")
DEFAULT_WEIGHTS = Path("checkpoints")
DEFAULT_RESULTS = Path("results/base-vs-tuned")
DATASET_REPO = "state-lifetime-tutor-v1"
SPACE_REPO = "state-lifetime-tutor-demo"
DEFAULT_SPACE = Path("space")


def render_dataset_card(repo_id: str, n_examples: int, curve_points: list[int]) -> str:
    """Render the dataset card.

    Carries the caveats forward from the repo README rather than presenting the pool as
    something it is not. The brief calls the dataset the real artifact; an artifact that
    oversells its own provenance is worth less than one that does not.

    Args:
        repo_id: The dataset's Hub id, used in the usage example.
        n_examples: Size of the published pool.
        curve_points: Sizes with an id manifest.

    Returns:
        A Markdown dataset card with YAML frontmatter.
    """
    points = ", ".join(f"`n-{n}`" for n in curve_points)
    return f"""---
license: apache-2.0
language:
  - en
task_categories:
  - text-generation
tags:
  - synthetic
  - python
  - tutoring
  - sft
size_categories:
  - n<1K
---

# Python State-Lifetime Tutor — training set v1

{n_examples} synthetic examples that teach one behavior: given a short Python program with
one mutable-state lifetime bug, quote or identify the relevant declaration, assignment, or
mutation and ask **exactly one** non-compound question about when the object is created,
who owns it, or which references share it — never emitting corrected code or stating the
correction.

## Files

| Path | What |
|---|---|
| `sft-v1.jsonl` | TRL-ready chat format, `{{"messages": [system, user, assistant]}}` |
| `pool-v1.jsonl` | Canonical pool: full scenario, on-spec response, near-miss, provenance |
| `curve/n-*.txt` | Id manifests for the data-efficiency curve ({points}) |
| `raw/` | Every candidate plus rejections — the rejections double as DPO preference pairs |
| `audit-v1.jsonl` | Frozen-judge transcripts for a 10% sample |

## Design

Balanced across a 40-cell grid of `lifetime_concept × code_shape × category`, with a
`seed_domain` axis so the student learns the bug shape rather than the variable names.
Two-thirds clean, one-third adversarial, matching the eval set's ratio.

Labels are assigned **by construction** — each example is authored into a requested cell
rather than generated and labelled afterwards. Ranks are assigned so that every prefix of
the pool stays balanced, which is what makes the curve subsets nested: `n-62` is a strict
subset of `n-125`, and so on, so dataset size is the only variable between curve points.

Every candidate passed the same gate: AST validation that the program structurally exhibits
its declared concept, contamination checking against the held-out eval set, mechanical
screening of the response against the behavior spec, and dedupe on normalized code and
student message.

## Caveats

- **The v1 rows were authored in-session, not generated by the teacher script.** The
  generation script implements the same taxonomy and the same gate and is smoke-tested
  against a live teacher, but it did not produce these rows. Every row records which path
  produced it in `provenance.author`.
- **Single-context authoring is a real diversity risk.** Independent high-temperature
  sampling is the usual diversity mechanism and one context has neither. Mitigated by
  cell-by-cell authoring, an explicit domain per example, and normalized-code dedupe — and
  measurable, since the eval set is independent.
- **The training filter is deliberately stricter than the eval judge**, flagging any
  `and`/`or` inside a question clause. That over-rejects some legitimate phrasing on
  purpose: compound questions were the dominant failure mode of every prompted frontier
  model tested.
- **Label-by-construction means the gate rejects little.** The quality claim rests on the
  AST, contamination, and mechanical checks plus the judge audit — not on a high reject
  count.

## Usage

```python
from datasets import load_dataset

ds = load_dataset("{repo_id}", data_files="sft-v1.jsonl", split="train")
```
"""


def resolve_metrics(
    metrics: dict[str, dict[str, Any]], repo_id: str
) -> dict[str, Any] | None:
    """Find a checkpoint's metrics, tolerating an eval that ran against local weights.

    `eval.py` keys trials by whatever `--model` was given. When the Hub copy cannot be
    downloaded - a full disk, an offline grader - the eval runs against a local directory
    instead, and the recorded id is a path rather than a repo id. A local directory whose
    final path segment is a suffix of the repo name is the same checkpoint, so the card
    still gets its numbers.

    Args:
        metrics: Per-model metric tables from `eval_metrics`.
        repo_id: The Hub repo the card is being written for.

    Returns:
        The matching metric table, or None if this checkpoint has not been evaluated.
    """
    if repo_id in metrics:
        return metrics[repo_id]
    for key, table in metrics.items():
        if repo_id.endswith(key.rsplit("/", maxsplit=1)[-1]):
            return table
    return None


def eval_metrics(results_dir: Path) -> dict[str, dict[str, Any]]:
    """Read the latest base-vs-tuned scores, keyed by model id.

    A model card without numbers is a claim; the point of publishing is that the claim
    arrives attached to its evidence. Absent results are not an error - the first push
    happens before the eval has run.

    Args:
        results_dir: Directory holding `trials.jsonl` from `eval.py`.

    Returns:
        Per-model metric tables, empty if no eval has been run yet.
    """
    trials_path = results_dir / "trials.jsonl"
    if not trials_path.exists():
        return {}
    trials = [
        Trial.model_validate_json(line)
        for line in trials_path.read_text().splitlines()
        if line.strip()
    ]
    return {
        cell.model_id: {
            "Spec adherence (24 clean)": f"{cell.spec_adherence:.0%}",
            "Robustness (12 adversarial)": f"{cell.robustness:.0%}",
            "Mechanical check pass": f"{cell.mechanical_pass_rate:.0%}",
        }
        for cell in aggregate(trials)
    }


def main() -> None:
    """Publish the dataset, model cards, and demo Space to the Hugging Face Hub."""
    parser = argparse.ArgumentParser(description="Publish artifacts to the Hub")
    parser.add_argument("--dataset", action="store_true", help="Publish data/train/")
    parser.add_argument(
        "--models",
        action="store_true",
        help="Push any checkpoint that has local weights but no revision, then write cards",
    )
    parser.add_argument("--cards", action="store_true", help="Rewrite model cards only")
    parser.add_argument("--space", action="store_true", help="Deploy the Gradio demo Space")
    parser.add_argument("--space-dir", type=Path, default=DEFAULT_SPACE)
    parser.add_argument(
        "--tuned",
        default=None,
        help="Checkpoint the Space demos; defaults to the largest recorded one",
    )
    parser.add_argument(
        "--logs",
        type=Path,
        default=Path("results/train"),
        help=(
            "Training logs to build cards from. Must match the dataset revision being "
            "carded: run logs are keyed by size alone, so pointing this at results/train "
            "while carding v2 describes a v2 checkpoint with v1's training run."
        ),
    )
    parser.add_argument(
        "--match",
        default="",
        help="Only touch checkpoints whose repo id contains this substring, e.g. '-v2'",
    )
    parser.add_argument(
        "--dataset-repo",
        default=DATASET_REPO,
        help=(
            "Hub dataset name (without the namespace) to publish to and to cite in model "
            "cards. Must be set alongside --data when publishing a second dataset "
            "revision, or the v2 cards cite the v1 dataset."
        ),
    )
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--weights", type=Path, default=DEFAULT_WEIGHTS)
    parser.add_argument("--checkpoints", type=Path, default=DEFAULT_CHECKPOINTS)
    parser.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    parser.add_argument("--hf-user", default=None, help="Hub namespace; defaults to $HF_USER")
    parser.add_argument(
        "--private", action="store_true", help="Create repos private (default is public)"
    )
    args = parser.parse_args()

    load_env_file()
    hf_user = args.hf_user or os.environ.get("HF_USER")
    if not hf_user:
        raise SystemExit("set HF_USER in .env or pass --hf-user")
    if not (args.dataset or args.models or args.cards or args.space):
        raise SystemExit("nothing to do: pass --dataset, --models, --cards, or --space")

    dataset_repo = f"{hf_user}/{args.dataset_repo}"

    if args.dataset:
        pool = load_pool(args.data / "pool-v1.jsonl")
        points = sorted(
            int(p.stem.removeprefix("n-")) for p in (args.data / "curve").glob("n-*.txt")
        )
        sha = upload_directory(dataset_repo, args.data, "dataset", private=args.private)
        upload_card(
            dataset_repo,
            render_dataset_card(dataset_repo, len(pool), points),
            repo_type="dataset",
        )
        print(f"dataset -> https://huggingface.co/datasets/{dataset_repo} @ {sha}")

    if args.models or args.cards:
        checkpoints = load_checkpoints(args.checkpoints)
        if not checkpoints:
            raise SystemExit(f"no checkpoints recorded in {args.checkpoints}")
        metrics = eval_metrics(args.results)
        for checkpoint in checkpoints:
            if args.match and args.match not in checkpoint.repo_id:
                continue
            run_json = args.logs / f"n-{checkpoint.dataset_size}" / "run.json"
            if not run_json.exists():
                print(f"  ! no run log for n={checkpoint.dataset_size}, skipping")
                continue
            result = TrainResult.model_validate_json(run_json.read_text())

            if args.models and checkpoint.revision is None:
                result.revision = push_checkpoint(result, private=args.private)
            else:
                result.revision = checkpoint.revision

            result.revision = upload_card(
                checkpoint.repo_id,
                render_model_card(
                    result,
                    checkpoint.base_model,
                    dataset_repo,
                    resolve_metrics(metrics, checkpoint.repo_id),
                ),
            )
            record_checkpoint(
                checkpoint.model_copy(update={"revision": result.revision}),
                args.checkpoints,
            )
            print(
                f"model   -> https://huggingface.co/{checkpoint.repo_id} "
                f"@ {result.revision}"
            )


    if args.space:
        checkpoints = load_checkpoints(args.checkpoints)
        if not checkpoints and args.tuned is None:
            raise SystemExit("no checkpoint to demo: train one, or pass --tuned")
        tuned = args.tuned or max(checkpoints, key=lambda c: c.dataset_size).repo_id
        space_repo = f"{hf_user}/{SPACE_REPO}"
        sha = upload_directory(
            space_repo, args.space_dir, "space", private=args.private, space_sdk="gradio"
        )
        # The demo target is a variable rather than a code edit, so pointing the Space at a
        # different curve point costs a settings change instead of a redeploy.
        set_space_variable(space_repo, "TUNED_MODEL", tuned)
        print(f"space   -> https://huggingface.co/spaces/{space_repo} @ {sha}")
        print(f"           demoing {tuned}")


if __name__ == "__main__":
    main()
