from __future__ import annotations

import argparse
import os
from pathlib import Path

from slm.checkpoints import DEFAULT_CHECKPOINTS, load_checkpoints, record_checkpoint
from slm.config import load_env_file
from slm.dataset import load_pool
from slm.publishing import (
    push_checkpoint,
    render_model_card,
    upload_card,
    upload_directory,
)
from slm.training import TrainResult

DEFAULT_DATA = Path("data/train")
DEFAULT_WEIGHTS = Path("checkpoints")
DATASET_REPO = "state-lifetime-tutor-v1"


def render_dataset_card(repo_id: str, n_examples: int, curve_points: list[int]) -> str:
    """Render the dataset card.

    Carries the caveats forward from the repo README rather than presenting the pool as
    something it is not. The brief calls the dataset the real artifact; an artifact that
    oversells its own provenance is worth less than one that does not.

    Args:
        repo_id: The dataset's Hub id, used in the usage example.
        n_examples: Size of the published pool.
        curve_points: Sizes with an id manifest.

    Returns:
        A Markdown dataset card with YAML frontmatter.
    """
    points = ", ".join(f"`n-{n}`" for n in curve_points)
    return f"""---
license: apache-2.0
language:
  - en
task_categories:
  - text-generation
tags:
  - synthetic
  - python
  - tutoring
  - sft
size_categories:
  - n<1K
---

# Python State-Lifetime Tutor — training set v1

{n_examples} synthetic examples that teach one behavior: given a short Python program with
one mutable-state lifetime bug, quote or identify the relevant declaration, assignment, or
mutation and ask **exactly one** non-compound question about when the object is created,
who owns it, or which references share it — never emitting corrected code or stating the
correction.

## Files

| Path | What |
|---|---|
| `sft-v1.jsonl` | TRL-ready chat format, `{{"messages": [system, user, assistant]}}` |
| `pool-v1.jsonl` | Canonical pool: full scenario, on-spec response, near-miss, provenance |
| `curve/n-*.txt` | Id manifests for the data-efficiency curve ({points}) |
| `raw/` | Every candidate plus rejections — the rejections double as DPO preference pairs |
| `audit-v1.jsonl` | Frozen-judge transcripts for a 10% sample |

## Design

Balanced across a 40-cell grid of `lifetime_concept × code_shape × category`, with a
`seed_domain` axis so the student learns the bug shape rather than the variable names.
Two-thirds clean, one-third adversarial, matching the eval set's ratio.

Labels are assigned **by construction** — each example is authored into a requested cell
rather than generated and labelled afterwards. Ranks are assigned so that every prefix of
the pool stays balanced, which is what makes the curve subsets nested: `n-62` is a strict
subset of `n-125`, and so on, so dataset size is the only variable between curve points.

Every candidate passed the same gate: AST validation that the program structurally exhibits
its declared concept, contamination checking against the held-out eval set, mechanical
screening of the response against the behavior spec, and dedupe on normalized code and
student message.

## Caveats

- **The v1 rows were authored in-session, not generated by the teacher script.** The
  generation script implements the same taxonomy and the same gate and is smoke-tested
  against a live teacher, but it did not produce these rows. Every row records which path
  produced it in `provenance.author`.
- **Single-context authoring is a real diversity risk.** Independent high-temperature
  sampling is the usual diversity mechanism and one context has neither. Mitigated by
  cell-by-cell authoring, an explicit domain per example, and normalized-code dedupe — and
  measurable, since the eval set is independent.
- **The training filter is deliberately stricter than the eval judge**, flagging any
  `and`/`or` inside a question clause. That over-rejects some legitimate phrasing on
  purpose: compound questions were the dominant failure mode of every prompted frontier
  model tested.
- **Label-by-construction means the gate rejects little.** The quality claim rests on the
  AST, contamination, and mechanical checks plus the judge audit — not on a high reject
  count.

## Usage

```python
from datasets import load_dataset

ds = load_dataset("{repo_id}", data_files="sft-v1.jsonl", split="train")
```
"""


def main() -> None:
    """Publish the dataset, model cards, and demo Space to the Hugging Face Hub."""
    parser = argparse.ArgumentParser(description="Publish artifacts to the Hub")
    parser.add_argument("--dataset", action="store_true", help="Publish data/train/")
    parser.add_argument(
        "--models",
        action="store_true",
        help="Push any checkpoint that has local weights but no revision, then write cards",
    )
    parser.add_argument("--cards", action="store_true", help="Rewrite model cards only")
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--weights", type=Path, default=DEFAULT_WEIGHTS)
    parser.add_argument("--checkpoints", type=Path, default=DEFAULT_CHECKPOINTS)
    parser.add_argument("--hf-user", default=None, help="Hub namespace; defaults to $HF_USER")
    parser.add_argument(
        "--private", action="store_true", help="Create repos private (default is public)"
    )
    args = parser.parse_args()

    load_env_file()
    hf_user = args.hf_user or os.environ.get("HF_USER")
    if not hf_user:
        raise SystemExit("set HF_USER in .env or pass --hf-user")
    if not (args.dataset or args.models or args.cards):
        raise SystemExit("nothing to do: pass --dataset, --models, or --cards")

    dataset_repo = f"{hf_user}/{DATASET_REPO}"

    if args.dataset:
        pool = load_pool(args.data / "pool-v1.jsonl")
        points = sorted(
            int(p.stem.removeprefix("n-")) for p in (args.data / "curve").glob("n-*.txt")
        )
        sha = upload_directory(dataset_repo, args.data, "dataset", private=args.private)
        upload_card(
            dataset_repo,
            render_dataset_card(dataset_repo, len(pool), points),
            repo_type="dataset",
        )
        print(f"dataset -> https://huggingface.co/datasets/{dataset_repo} @ {sha}")

    if args.models or args.cards:
        checkpoints = load_checkpoints(args.checkpoints)
        if not checkpoints:
            raise SystemExit(f"no checkpoints recorded in {args.checkpoints}")
        for checkpoint in checkpoints:
            run_json = Path("results/train") / f"n-{checkpoint.dataset_size}" / "run.json"
            if not run_json.exists():
                print(f"  ! no run log for n={checkpoint.dataset_size}, skipping")
                continue
            result = TrainResult.model_validate_json(run_json.read_text())

            if args.models and checkpoint.revision is None:
                result.revision = push_checkpoint(result, private=args.private)
                record_checkpoint(
                    checkpoint.model_copy(update={"revision": result.revision}),
                    args.checkpoints,
                )
            else:
                result.revision = checkpoint.revision

            upload_card(
                checkpoint.repo_id,
                render_model_card(result, checkpoint.base_model, dataset_repo),
            )
            print(
                f"model   -> https://huggingface.co/{checkpoint.repo_id} "
                f"@ {result.revision or 'not pushed'}"
            )


if __name__ == "__main__":
    main()
